# kubectl ai "create pod name=app add labels app=demo, run=demo image gcr.io/symmetric-ray-404110/demo:v2.0.0 container port 3000 port name http"
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
    - name: app
      image: gcr.io/symmetric-ray-404110/demo:v2.0.0
      ports:
        - containerPort: 3000
          name: http