# kubectl ai "create pod image redis set up secret username and password envs"
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>