# kubectl ai "create pod with liveness and rediness probs on port 3000 use kuard image. resources cpu 100m, memory 128"
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    ports:
    - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /
        port: 3000
    readinessProbe:
      httpGet:
        path: /
        port: 3000