# kubectl ai "create hello world cron job run each 5 min image bash command echo Hello world"
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world-container
              image: bash
              command: ["echo", "Hello world"]
          restartPolicy: OnFailure